### ISSUE TITLE
Support for multiple security parameters for receiving v3 TRAPs 

### ISSUE THREAD

**Issue by balasankarrajaguru** [gosnmp/gosnmp#302]
Description : 
  The current trap listener in gosnmp has only one security parameter configuration associated with it. The requirement is to support multiple security parameter configuration and the security parameter for the incoming packet is identified after parsing the SecurityEngineID and SecurityName which will will be looked up in the USM table(security parameters Map) to identify the correct security parameter to identify the configuration.

**Comment by balasankarrajaguru** [comment]
I'm planning to work on this. Suggestions are welcome

**Comment by TimRots** [comment]
> I'm planning to work on this.

Thank you @balasankarrajaguru. I assigned the issue to you.

>> Suggestions are welcome

Will post back later with some notes

**Comment by mark-chandler** [comment]
Hi @balasankarrajaguru - do you have any updates to this issue?
I think it may be contributing to an [issue](https://github.com/influxdata/telegraf/issues/13414) that I have with Telegraf

**Comment by zoedt** [comment]
@TimRots would be curious if you still have any notes - I'm thinking of working on this myself

**Comment by zoedt** [comment]
cc @SuperQ if any thoughts from your end as well as I see you're another active maintainer on the repo !

So far, it seems clear there should be some introduction of some mapping to keep track of either engineID/username to security parameters. However, to get that information to map correctly when receiving a trap, it looks like unmarshalling the header of the packet with this method is needed (with security parameters of no auth/no priv because we're not interested in actually doing anything except getting those certain fields to get the correct security parameters to authenticate/decrypt with). I see we have to process with the cursor to be able to reach the correct points for fields we're interested in, unless we can manipulate the order for the `SnmpPacket` / `SecurityParameters` so that the username or engine ID may be first and be able to be utilized before proceeding to unmarshal the rest of it (and be able to switch to the SecurityParameters the trap would be for)

Not sure if there's anything I'm missing in my understanding, please let me know if there's any gaps in my knowledge or constraints to keep in mind. Thank you!
