### ISSUE TITLE
Connect function in gosnmp always returns nil even if the credentials are not valid

### ISSUE THREAD

**Issue by aneesurrehman001** [gosnmp/gosnmp#439]
When I pass wrong credentials for V3 request such as username, password, etc. I am expecting it to return me an error message that tells me what went wrong while establishing a connection with the remote host such as "authentication failed: Wrong password for the user xyz" before it proceeds with the SNMP get/walk/etc requests, but it always returns "nil" and continues with the script. 

`err := g.Default.Connect()
	if err != nil {
		log.Fatalf("Connect() err: %v", err)
}`

@soniah

**Comment by sumitroajiprabowo** [comment]
same issue i set snmp host but return nil

**Comment by sumitroajiprabowo** [comment]
func (x *[GoSNMP]

Connect creates and opens a socket. Because UDP is a connectionless protocol, you won't know if the remote host is responding until you send packets. Neither will you know if the host is regularly disappearing and reappearing.

please check [this link](https://github.com/gosnmp/gosnmp/blob/v1.36.1/gosnmp.go#L272)
